/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbc9",
        "on-error": "#ffffff",
        "surface-container-low": "#edf4ff",
        "on-background": "#091d2e",
        "on-tertiary-fixed": "#221b00",
        "surface-dim": "#c9dcf3",
        "error": "#ba1a1a",
        "tertiary": "#705d00",
        "on-secondary-container": "#672c00",
        "surface-container-high": "#d9eaff",
        "secondary-fixed-dim": "#ffb68d",
        "on-primary-container": "#5f1900",
        "inverse-on-surface": "#e8f2ff",
        "background": "#f7f9ff",
        "outline": "#8d7168",
        "surface-variant": "#d1e4fb",
        "on-surface-variant": "#594139",
        "outline-variant": "#e1bfb5",
        "on-secondary-fixed-variant": "#763300",
        "on-primary-fixed-variant": "#832600",
        "secondary-container": "#fc8a40",
        "primary": "#ab3500",
        "surface": "#f7f9ff",
        "primary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#e9c400",
        "surface-bright": "#f7f9ff",
        "on-tertiary-container": "#4c3e00",
        "on-primary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#544600",
        "on-surface": "#091d2e",
        "surface-container": "#e3efff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb59d",
        "tertiary-container": "#c9a900",
        "primary-fixed-dim": "#ffb59d",
        "error-container": "#ffdad6",
        "primary-container": "#ff6b35",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#331200",
        "inverse-surface": "#203243",
        "surface-container-highest": "#d1e4fb",
        "tertiary-fixed": "#ffe16d",
        "secondary": "#9b4500"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "Cairo"],
        "body": ["Work Sans", "Cairo"],
        "label": ["Work Sans", "Cairo"],
        "arabic": ["Cairo", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
